---
- hosts: localhost
  become: false
  tasks:
    - name: install galaxy roles
      command: ansible-galaxy install -r requirements.yml --roles-path galaxy_roles
    - name: ensure roles folder is gitignored
      lineinfile:
        dest:   .gitignore
        regexp: '^galaxy_roles$'
        line:   'galaxy_roles'
        state:  present
