---
# install/remove packages
- hosts: all
  gather_facts: yes
  roles:
    - role: zerotao.packages
      tags:
        - packages
    - role: AsavarTzeth.users
      tags:
        - users
# configure users

- hosts: all
  gather_facts: yes
  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.java
  tags:
    - common

- hosts: jenkins_servers
  gather_facts: yes
  roles:
    - geerlingguy.jenkins
  tags:
    - jenkins

# - hosts: jira_servers
#   gather_facts: yes

#   roles:
#     - geerlingguy.jenkins
#   tags:
#     - jira
