---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  gather_facts: yes
  roles:
     - role: zerotao.packages
       packages_add:
         - tmux
         - vim
         - lsof
       packages_remove:
         - build-essential
  tags:
    - packages

- hosts: all
  gather_facts: yes
  roles:
    - role: geerlingguy.firewall
      tags: firewall
      when: install_firewall
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.java
  tags:
    - common

- hosts: jenkins_servers
  gather_facts: yes
  roles:
    - geerlingguy.jenkins
  tags:
    - jenkins

# - hosts: jira_servers
#   gather_facts: yes

#   roles:
#     - geerlingguy.jenkins
#   tags:
#     - jira
