---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: all
  gather_facts: yes
  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
  tags:
    - common

- hosts: jenkins_servers
  gather_facts: yes
  roles:
    - geerlingguy.jenkins
  tags:
    - jenkins

# - hosts: jira_servers
#   gather_facts: yes

#   roles:
#     - geerlingguy.jenkins
#   tags:
#     - jira
