---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: check if python exists
      stat:
        path: /usr/bin/python
      register: python_file
    - name: 'install python2'
      raw: apt -y update && apt install -y python-minimal
      when: not python_file.stat.exists
  tags: ["prepare"]

# install/remove packages
- hosts: all
  gather_facts: yes
  roles:
    - role: zerotao.packages
      tags:
        - packages
    - role: AsavarTzeth.users
      tags:
        - users
    - role: hswong3i.jira
      tags: ["jira"]

- hosts: all
  gather_facts: yes
  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.java
  tags:
    - common

- hosts: jenkins_servers
  gather_facts: yes
  roles:
    - geerlingguy.jenkins
  tags:
    - jenkins

- hosts: jira_servers
  gather_facts: yes
  roles:
    - hswong3i.jira
  tags:
    - jira
